feat(reports): 050724 contributors report
TOSIT-IO/tdp-website pull request #103
Opened 2024-07-05 14:08 UTC by SteBaum

Contributors' report of 5th of July 2024.

2024-07-06 07:45 UTC, wdavidw requested changes

2024-07-06 07:45 UTC, wdavidw commented on content/reports/240705-contributors.md
> +PR tdp-collection#850 and the use of Alluxio
dot at the end of sentences

2024-07-06 07:45 UTC, wdavidw commented on content/reports/240705-contributors.md
> +Work on the integration of PrestoSQL has started. However, Alluxio might be used instead as it will work more efficiently with Hive as it uses a cache and will run with Yarn, has better capacity sche
Split the second sentence into 3 sentences. "However, Alluxio might be used instead. Its usage by Hive is of particular interest, leveraging its cache layer and YARN integration. Additionally, we are interested by its capacity scheduling for multiple users as well as its ability to manage S3 permissions with Ranger."

2024-07-09 09:07 UTC, wdavidw approved these changes

2024-07-12 12:27 UTC, merged

2024-07-12 12:28 UTC, omazain commented
Je suis absent du 28 juin 2024 au 19 juillet 2024 inclus. En cas d'urgence, merci de contacter Madame Florence THILLAY

2024-07-12 12:30 UTC, abeguec commented
Je suis absente du 01 juillet 2024 au 17 juillet 2024 inclus. Si besoin, vous pouvez contacter Mme Florence Thillay

2024-07-12 12:30 UTC, nviault-dgfip commented
Je suis absent du 01 juillet 2024 au 12 juillet 2024 inclus.