docs(pages): roadmap
TOSIT-IO/tdp-website pull request #46
Opened 2023-10-06 08:05 UTC by wdavidw

Present the project roadmap with current and future actions lead by the community.

2023-10-06 08:16 UTC, abeguec commented
à discuter si les autres son ok : aborder le long terme sur la doc : pourquoi pas mais si cela n'arrive pas cela risque de faire mauvaise impression..
- dans  'stack' : perso je n'aime pas le terme actif pour le développement mais cela a peut être une signification précise. De même on peut supprimer la parenthèse sur la version 2.. on verra le numéro plus tard vu les longues discussions à chaque fois sur ce sujet
- -UI: peut être mentionné que des travaux vont reprendre avec des conseils d'ergonomie et d’accessibilité pour se mettre en conformité avec le RGAA 4.1?

2023-10-06 08:26 UTC, Edouard-R requested changes
Let's not talk about v2

2023-10-06 09:16 UTC, PACordonnier commented
(J'ai collaboré au premier commit avec @wdavidw)

Je répond aux quelques points abordés précédemment mais on pourra aborder le sujet de vive voix.

> aborder le long terme sur la doc : pourquoi pas mais si cela n'arrive pas cela risque de faire mauvaise impression..

C'est sûr, mais c'est une première étape :)

> -UI: peut être mentionné que des travaux vont reprendre avec des conseils d'ergonomie et d’accessibilité pour se mettre en conformité avec le RGAA 4.1?

Ajouté dans le dernier commit

> Stack V2

Je suis OK pour dire que le terme stack 2.X n'est pas satisfaisant. Je pense néanmoins qu'aborder le sujet dans la Roadmap d'une mise à jour de la plateforme pour se distinguer d'une distribution calqué sur HDP est pertinent.

2023-10-09 05:47 UTC, abeguec approved these changes

2023-10-11 14:04 UTC, rpignolet requested changes
Enlever la mention de la version 2. Pour l'instant seule la version 1.1 est prévue. Rien n'a pour l'instant été décidé concernant la version après la 1.1.
On focus toutes les ressources sur la sortie de la version 1.1. On verra après sa sortie ce qu'on fait.

2023-10-12 10:05 UTC, wdavidw commented
> Enlever la mention de la version 2. Pour l'instant seule la version 1.1 est prévue. Rien n'a pour l'instant été décidé concernant la version après la 1.1. On focus toutes les ressources sur la sortie de la version 1.1. On verra après sa sortie ce qu'on fait.

[Version 2 is removed](7a42f1c29812010a608771c343316c5e3d0a48c0).

Note, for everyone who wish to contribute to this page. This is a roadmap, not an engagement letter. As such, we shall provide a maximum of transparancy on what is our current focus and not by shy to share what are the future evolution to be discussed and assessed in the coming weeks, 1.1 coming soon.

2023-10-20 07:13 UTC, rpignolet approved these changes

2023-10-23 19:51 UTC, wdavidw commented
Seems like we got 2 approvals, can we merge ?

2023-10-24 07:51 UTC, rpignolet commented
No we wait @Edouard-R approval

2023-10-24 08:10 UTC, Edouard-R approved these changes

2023-10-24 08:14 UTC, merged